name: simple_example
dependencies:
   polymer_element: '^2.0.6'
   polymer_elements:
     git:
       url: https://github.com/polymer-dart/polymerize_elements.git
       ref: v0.3.4
dev_dependencies:
  polymerize: '^0.9.5'
transformers:
  - polymerize:
     entry-point: web/main.dart
web:
  compiler:
    debug: dartdevc
    release: dartdevc